### PR TITLE
Upgrade to Solidity 0.4.x

### PR DESCRIPTION
**Pull request by adibas03**
- upgrade npm packages
- upgrade contracts to 0.4.24
- Remove deprecated code

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks! Let's upgrade `solidity-parser` while we're at it, then should be good to go!

**Comment by raineorshine** [comment]
Actually, it does look like it’s going to take a little more work to get it to parse the newer syntax. It’s most likely an update needed to `solidity-parser`. I created a failing unit test in `master` that you can use to see where it fails to parse the new "emit" keyword (as mentioned in #19).

**Comment by adibas03** [comment]
I would look into that.
I am also considering the option of switching `solidity-parser` to `truffle-artifactor` or `solidity-parser-antlr` since it has not been updated since August, last year.

**Comment by raineorshine** [comment]
We should also consider merging #17 once a unit test is added.

**Comment by stefek99** [comment]
> since it has not been updated since August, last year

Yeah, many open issues too: https://github.com/ConsenSys/solidity-parser/issues

I'm here because of the DEFCON talk: https://www.youtube.com/watch?v=WIEessi3ntk

_(always learning, decentralize everything)_

**Comment by adibas03** [comment]
@raineorshine As at https://github.com/raineorshine/solgraph/pull/20/commits/a58d66f898eb6ba25c230d142a2b40798bc78182 , All tests are passing.
The next steps have begun, which include:
** TODO **
- Switch `solidity-parser` to `solidity-parser-antlr` 
- Uncomment `emit` test, it is disabled since `solidityparser does not recognize the `emit` key word.

**Comment by adibas03** [comment]
Will use ~https://github.com/raineorshine/solgraph/pull/23~ to track switch between parser,
as well as adding `emit` keyword
you can squash this in, if no updates

**Update:**
parer-switch ready at https://github.com/raineorshine/solgraph/pull/24
using `solidity-parser-sc` instead, which is an updated fork of `solidity-parser`

**Comment by raineorshine** [comment]
Great, thank you! I'm glad the parser from https://github.com/sc-forks/solidity-parser works as-is.

I think the main thing we need in this PR now are the tests for the newer solidity features:

- multi-variable assignments (#7)
- object construction (#12)
- parse errors (#16)
- more parse errors (#21)

Once we have tests that demonstrate that the parse errors are all gone, we should be good to merge! Would you like to do that in this PR or in a separate one?

**Comment by adibas03** [comment]
I think a separate PR will be better to keep things, fine-grained

**Comment by raineorshine** [comment]
Thank you @adibas03 for all your help! Looks like #26 is a bit more comprehensive, so I merged that one. It would still be great to confirm the resolution of the above-mentioned issues and add any missing tests that are needed.

**Comment by adibas03** [comment]
Apologies for the late response.
> It would still be great to confirm the resolution of the above-mentioned issues and add any missing tests that are needed.  

Sounds good, I would check it out.

**Pull request closed without merging**
